export const LOAD_DOGS_SUCCESS = "LOAD_DOGS_SUCCESS";
export const CREATE_DOG_SUCCESS = "CREATE_DOG_SUCCESS";
export const UPDATE_DOG_SUCCESS = "UPDATE_DOG_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
